- name: Ensure elasticsearch group exists
  ansible.builtin.group:
    name: "{{ es_group }}"
    state: present
  become: yes

- name: Ensure elasticsearch user exists
  ansible.builtin.user:
    name: "{{ es_user }}"
    group: "{{ es_group }}"
    shell: /bin/bash
    state: present
  become: yes

