- name: Deploy certificates | CA
  tags: conf, certificates
  copy:
    src: ./certs/{{ ssl_ca }}
    dest: "{{ es_conf_dir }}/{{ ssl_ca }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: '0400'
    backup: yes

- name: Deploy certificates | Server Certificate
  tags: conf, certificates
  copy:
    src: ./certs/{{ ssl_cert }}
    dest: "{{ es_conf_dir }}/{{ ssl_cert }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: '0400'
    backup: yes

- name: Deploy certificates | Server Cert Key
  tags: conf, certificates
  copy:
    src: ./certs/{{ ssl_key }}
    dest: "{{ es_conf_dir }}/{{ ssl_key }}"
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: '0400'
    backup: yes

