- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: '0755'
  loop:
    - "{{ es_bin_dir }}"
    - "{{ es_conf_dir }}"
    - "{{ es_data_dir }}"
    - "{{ es_logs_dir }}"
    - "{{ es_repo_dir }}"
    - "{{ es_conf_dir }}/jvm.options.d"
